# Generated by Django 5.2.11 on 2026-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('complete', 'Complete')], default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
