# Generated by Django 5.2.11 on 2026-03-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_task_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
