# Generated by Django 5.2.11 on 2026-03-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
