# Generated by Django 5.2.11 on 2026-03-03 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_permission_id_alter_role_id_alter_workspace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='workspace',
        ),
        migrations.AddField(
            model_name='workspace',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspace.workspace'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
