# Generated by Django 5.2.11 on 2026-03-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_remove_role_workspace_workspace_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
